services:
  backend:
    image: app:2
    container_name: petclinic
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8081:8080"
  mysqldb:
    image: mysql:5.7.8
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=petclinic
      - MYSQL_ROOT_PASSWORD=petclinic
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
  